webpizza/applipizza/urls.py
from django.urls import path
from applipizza import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home),
    path('pizzas/', views.pizzas),
    path('ingredients/', views.ingredients),
    path('pizzas/<int:pizza_id>/', views.pizza),
    path('ingredients/add/', views.formulaireCreationIngredient),
    path('ingredients/create/', views.creerIngredient),
    path('pizzas/add/', views.formulaireCreationPizza),
    path('pizzas/create/', views.creerPizza),
    path('pizzas/<int:pizza_id>/addIngredient/', views.ajouterIngredientDansPizza),
    path('pizzas/<int:pizza_id>/delete/', views.supprimerPizza),
    path('pizzas/<int:pizza_id>/update/', views.afficherFormulaireModificationPizza),
    path('pizzas/<int:pizza_id>/updated/', views.modifierPizza),
    path('ingredients/<int:ingredient_id>/delete/', views.supprimerIngredient),
    path('ingredients/<int:ingredient_id>/update/', views.afficherFormulaireModificationIngredient),
    path('ingredients/<int:ingredient_id>/updated/', views.modifierIngredient),
    path('pizzas/<int:pizza_id>/deleteIngredient/<int:composition_id>/',views.supprimerIngredientDansPizza),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

webpizza/webpizza/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applipizza.urls')),
    path('', include('applicompte.urls')),
    path('', include('applipanier.urls')),
    path('', include('applistats.urls')),
]

webpizza/applipizza/models.py
from django.db import models

# Create your models here.

class Ingredient(models.Model) :

    #idIngredient est une clé primaire, n auto-increment => AutoField
    idIngredient = models.AutoField(primary_key = True)

    #idIngredient est une chaine de caractères => CharField
    nomIngredient = models.CharField(max_length = 50, verbose_name = '''le nom de l'ingrédient''')

    # une méthode de type toString()
    def __str__(self) -> str : 
        return self.nomIngredient

class Pizza(models.Model) :

    #idPizza est une clé primaire, n auto-increment => AutoField
    idPizza = models.AutoField(primary_key = True)

    #nomPizza est une chaine de caractères => CharField
    nomPizza = models.CharField(max_length = 50, verbose_name = '''le nom de la pizza''')

    # le prix est décimal, maximum = 4 chiffres dont 2 décimales 
    prix = models.DecimalField ( max_digits = 4, decimal_places = 2, verbose_name = 'le prix')

    #image de la pizza 
    image = models.ImageField(default= 'imagesPizzas/default.png', upload_to='imagesPizzas/')

    # une méthode de type toString()
    def __str__(self) -> str : 
        return 'Pizza "' + self.nomPizza + '" (' + str(self.prix) + ' €)'

class Composition(models.Model) :
    #la classe Meta qui gère l'unicité du couple de clés étrangères 
    class Meta :
        unique_together = ('ingredient', 'pizza') # le nom des clés étrangères 

    #idComposition est la clé primaire
    idComposition = models.AutoField(primary_key = True)

    #les deux champs clés étrangères, dont les noms correspondent
    #aux classes respectives en minuscules
    ingredient = models.ForeignKey(Ingredient, on_delete = models.CASCADE)
    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)

    #l'autre champ, chaînes de caractères 
    quantite = models.CharField(max_length = 100, verbose_name = 'la quantité')

    #une méthode de type toString
    def __str__(self) -> str :
        ing = self.ingredient
        piz = self.pizza
        return ing.nomIngredient + ' fait partie de la pizza ' + piz.nomPizza + ' (quantite : ' + self.quantite + ')'

webpizza/applipizza/forms.py
from django import forms
from django.forms import ModelForm
from applipizza.models import Ingredient,Pizza, Composition

class IngredientForm(ModelForm):
    class Meta :
        model = Ingredient
        fields = ['nomIngredient']

class PizzaForm(ModelForm):
    class Meta :
        model = Pizza
        fields = ['nomPizza', 'prix']

class CompositionForm(ModelForm):
    class Meta :
        model = Composition
        fields = ['ingredient', 'quantite']

webpizza/applipizza/views.py
from django.shortcuts import render, redirect
#import des modèles
from applipizza.models import Pizza, Ingredient, Composition
from applicompte.models import PizzaUser
from applipizza.forms import IngredientForm, PizzaForm, CompositionForm
#import des user
from django.contrib.auth.models import User

# Create your views here.
def home(request):
    user = None
    if request.user.is_authenticated:
        user =  PizzaUser.objects.get(id = request.user.id)
    return redirect('/pizzas', user = user)


def pizzas(request) :
    user = None
    if request.user.is_authenticated:
        user =  PizzaUser.objects.get(id = request.user.id)
    #récuperation des pizzas de la bd -> même que ds le shell
    lesPizzas = Pizza.objects.all()

    #retouner l'emplacement du template, request pas utilisé
    #contenu calculé (lesPizzas) -> dict python
    return render (
        request,
        'applipizza/pizzas.html',
        {'pizzas': lesPizzas, "user" : user}
    )

def ingredients(request) :
    #creation du user 
    user= None

    # staff
    if request.user.is_staff :
        #récuperation des ingrédients de la bd -> même que ds le shell
        lesIngredients = Ingredient.objects.all()
        user = PizzaUser.objects.get(id = request.user.id)
        #retouner l'emplacement du template, request pas utilisé
        #contenu calculé (lesIngredients) -> dict python
        return render (
            request,
            'applipizza/ingredients.html',
            {'ingredients': lesIngredients, 'user' : user}
        )
    elif request.user.is_authenticated : 
        user = PizzaUser.objects.get(id = request.user.id)
        lesPizzas = Pizza.objects.all()
        return redirect('/pizzas/', user=user)
    else:
        return redirect('/login/', user=user)

def pizza(request, pizza_id) :
    user = None
    if request.user.is_authenticated : 
        user = PizzaUser.objects.get(id = request.user.id)
    # récupération de la pizza dont l'identifiant a été passé
    # en paramètre (c'est l'int pizza_id)
    laPizza = Pizza.objects.get(idPizza = pizza_id)

    # récupération des ingrédients entrant dans la composition de la pizza
    compo = Composition.objects.filter(pizza = pizza_id)

    # récupération de tous les ingrédients présent dans la BD
    ingredients = Ingredient.objects.all()

    # on crée un dictionnaire dont chaque item sera lui-même
    # un dictionnaire contenant :
    lesIngredients = [
        {
            'idCompo' :        c.idComposition,     # - l'identifiant de la composition (idComposition)
            'nomIngredient' : (Ingredient.objects.get(idIngredient = c.ingredient_id)).nomIngredient,    # - le nom de l'ingrédient
            'quantite' :      c.quantite      # - la quantité de l'ingrédient dans cette composition
        }
        for c in compo
    ]

    # on retourne l'emplacement du template, la pizza récupérée de la base
    # et la liste des ingrédients calculée ci-dessus
    return render (
        request,
        'applipizza/pizza.html',
        {
            'pizza': laPizza,
            'ingredientsPizza' : lesIngredients,
            'ingredients' : ingredients,
            'user' : user
        }
    )

def formulaireCreationIngredient(request):
    user = None
    if request.user.is_authenticated : 
        user = PizzaUser.objects.get(id = request.user.id)
    if request.user.is_staff:
        # indique l'emplacement du template
        return render (
            request,
            'applipizza/formulaireCreationIngredient.html',
            {'user' : user}
        )
    else:
        return redirect('/pizzas/', user)

def creerIngredient(request):
    user = None
    if request.user.is_authenticated : 
        user = PizzaUser.objects.get(id = request.user.id)
    if request.user.is_staff:
        # on récupère le formulaire
        form = IngredientForm(request.POST)

        #verifier si le fromulaire est valide 
        if form.is_valid():
            #récupération de la valeur nomIngredient
            #cleandata() permet d'éviter les injections
            nomIng = form.cleaned_data['nomIngredient']

            #creation d'un nouvelm ingrédient
            ing = Ingredient()

            #affectation de son attribut nomIngredient
            ing.nomIngredient = nomIng

            #enregistrement de l'ingrédient dans la BD
            ing.save()

            #on retourne l'emplacement de la vue (ou plutot du
            #template au sens de django)+ contenu calculé (dic python)
            return render (
                request,
                'applipizza/traitementFormulaireCreationIngredient.html',
                {"nom" : nomIng, 'user' : user}
            )
        else:
            return render(request, 'applipizza/FormulaireNonValide.html', {"erreurs" : form.errors})
    else:
        return redirect('/pizzas/', user=user)

def formulaireCreationPizza(request):
    user = None
    if request.user.is_authenticated : 
        user = PizzaUser.objects.get(id = request.user.id)
    if request.user.is_staff:
        # indique l'emplacement du template
        return render (
            request,
            'applipizza/formulaireCreationPizza.html',
            {"user" : user}
        )
    else:
        return redirect('/pizzas/', user=user)

def creerPizza(request):
    user = None
    if request.user.is_authenticated : 
        user = PizzaUser.objects.get(id = request.user.id)
    if request.user.is_staff:
        # on récupère le formulaire
        form = PizzaForm(request.POST)

        #verifier si le fromulaire est valide 
        if form.is_valid():
            #récupération de la valeur nomIngredient
            #cleandata() permet d'éviter les injections
            nomPiz = form.cleaned_data['nomPizza']
            prixPiz = form.cleaned_data['prix']
            image = request.FILES['image'] if 'image' in request.FILES else 'imagesPizzas/default.png'

            #creation d'une nouvelle pizza
            piz = Pizza()

            #affectation de son attribut nomIngredient
            piz.nomPizza = nomPiz
            piz.prix = prixPiz
            piz.image = image

            #enregistrement de l'ingrédient dans la BD
            piz.save()

            #on retourne l'emplacement de la vue (ou plutot du
            #template au sens de django)+ contenu calculé (dic python)
            return render (
                request,
                'applipizza/traitementFormulaireCreationPizza.html',
                {"nom" : nomPiz, "user" : user}
            )
        else:
            return render(request, 'applipizza/FormulaireNonValide.html', {"erreurs" : form.errors})
    else:
        return redirect('/pizzas/', user=user)

def ajouterIngredientDansPizza(request, pizza_id):
    user = None
    if request.user.is_authenticated : 
        user = PizzaUser.objects.get(id = request.user.id)
    if request.user.is_staff:
        # on récupère le formulaire
        form = CompositionForm(request.POST)

        #verifier si le fromulaire est valide 
        if form.is_valid():
            #récupération des données postées 
            ing = form.cleaned_data['ingredient']
            qte = form.cleaned_data['quantite']
            piz = Pizza.objects.get(idPizza = pizza_id)
            compoPizza = Composition.objects.filter(pizza = pizza_id)
            lesIngredientsDeLaPizza = ((ligne.ingredient) for ligne in compoPizza)

            #vérifier si pa déja présent dans la composition sinon le delete
            if ing in lesIngredientsDeLaPizza:
                compo = Composition.objects.filter(pizza = pizza_id, ingredient = ing)
                compo.delete()

            #creation de la nouvelle instance de la omposition et remplissage des attributs
            compo = Composition()
            compo.ingredient = ing
            compo.quantite = qte
            compo.pizza = piz
            compo.save() #sauvegarder dans la base

            # on retourne l'emplacement du template, la pizza récupérée de la base
            # et la liste des ingrédients calculée ci-dessus
            return redirect('/pizzas/'+str(pizza_id)+'/', user=user)
        else:
            return render(request, 'applipizza/FormulaireNonValide.html', {"erreurs" : form.errors})
    else:
        return redirect('/pizzas/', user=user)

def supprimerPizza(request, pizza_id):
    user = None
    if request.user.is_authenticated : 
        user = PizzaUser.objects.get(id = request.user.id)
    if request.user.is_staff:
        piz = Pizza.objects.get(idPizza = pizza_id)

        #supprmer la pizza
        piz.delete()
        return redirect('/pizzas/', user=user)
    else:
        return redirect('/pizzas/',user=user)

def afficherFormulaireModificationPizza(request, pizza_id):
    user = None
    if request.user.is_authenticated : 
        user = PizzaUser.objects.get(id = request.user.id)
    if request.user.is_staff:
        pizza_a_modifier = Pizza.objects.get(idPizza = pizza_id)
        return render(
            request,
            'applipizza/formulaireModificationPizza.html', 
            {'pizza' : pizza_a_modifier, "user" : user}
    )
    else:
        return redirect('/pizzas/', user)

def modifierPizza(request, pizza_id):
    user = None
    if request.user.is_authenticated : 
        user = PizzaUser.objects.get(id = request.user.id)
    if request.user.is_staff:
        piz = Pizza.objects.get(idPizza = pizza_id)

        #récupération de la pizza passée par le formulaire
        form = PizzaForm(request.POST, request.FILES, instance = piz)

        if form.is_valid():
            piz.image = request.FILES['image'] if 'image' in request.FILES else piz.image
            piz.save()
            return render(
                request,
                'applipizza/traitementFormulaireModificationPizza.html',
                {'pizza' : piz, "user" : user}
            )
        else:

webpizza/applipizza/templates/applipizza/FormulaireNonValide.html
<pre>{{erreurs}}</pre>

webpizza/applipizza/templates/applipizza/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width-device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'applipizza/css/style.css' %}">
    <link rel="icon" href="{% static 'applipizza/img/pizza.png' %}">
</head>

<body class="site">
    <header>
        {% if user.is_staff %}
        {% include 'applicompte/menuStaff.html' %}
        {% elif user.is_authenticated %}
        {% include 'applicompte/menuClient.html' %}
        {% else %}
        {% include 'applicompte/menuNonConnecte.html' %}
        {% endif %}
    </header>
    {% if user.is_staff %}
        {% include 'applipanier/dashboard.html' %}
    {% endif %}
            <main class="site-content container-fluid mt-5">

                {% block main %}{% endblock %}

            </main>
            {% if user.is_staff %}
        </div>
    </div>
    {% endif %}
            <div class="container{% if user.is_staff %}-fluid mx-4{% endif %}">
                <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top ">
                    {% include 'applipizza/footer.html' %}
                </footer>
            </div>
    
    <script src="{% static 'applipanier/js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
</body>

</html>

webpizza/applipizza/templates/applipizza/footer.html
{% load static %}
<!-- Copyright -->
        <p class="col-md-4 mb-0 text-muted">© 2023 | Copyright | Pizza Land, All rights reserved</p>

        <a href="#"><img class="bi me-2" src="{% static 'applipizza/img/pizza_no_b.png' %}" alt="Logo Pizza" width="30" height="24" class="d-inline-block align-text-top"></a>

        <ul class="nav foot col-md-4 justify-content-end">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Accueil</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pizzas</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Nos Tarifs</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
        </ul>
<!-- Copyright -->

webpizza/applipizza/templates/applipizza/formulaireCreationIngredient.html
{% extends 'applipizza/base.html' %}

{% block title %}Création ingrédient{% endblock %}

{% block main %}
<div class="container-fluid"><h2>Création d'un ingrédient</h2></div>
<hr>
<div class="container card m-3 card-pizza mx-auto p-3">
    <form action="/ingredients/create/" method="post">
        {% csrf_token %}
        <div class="mb-3">
        <label for="id_nomIngredient">Nom de l'ingrédient</label>
        <input type="text" class="form-control" name="nomIngredient" placeholder="tomates, ananas..." required id="id_nomIngredient" maxlength="50">
        </div>
        <button type="submit" class="btn btn-dark">Envoyer</button>
    </form>
</div>
{% endblock %}

webpizza/applipizza/templates/applipizza/formulaireCreationPizza.html
{% extends 'applipizza/base.html' %}

{% block title %}Création pizza{% endblock %}

{% block main %}
<div class="container-fluid"><h2>Création d'une pizza</h2></div>
<hr>
<div class="container card m-3 card-pizza mx-auto p-3">
    <form enctype="multipart/form-data" action="/pizzas/create/" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nomPizza" class="form-label">Nom de la pizza</label>
            <input type="text" class="form-control" name="nomPizza" required id="id_nomPizza" maxlength="50">
        </div>

        <div class="mb-3" class="form-label">
            <label for="id_prix_Pizza">Prix de la pizza</label>
            <input type="number" class="form-control" name="prix" required id="id_prix_Pizza" maxlength="50" step="any">
        </div>

        <div class="mb-3" class="form-label">
            <label for="id_image" >Fichier image</label>
            <input  class="form-control" name="image" type="file" id="id_image" accept="image/*" >
        </div>
        <button type="submit" class="btn btn-dark">Envoyer</button>
    </form>
</div>
{% endblock %}

webpizza/applipizza/templates/applipizza/formulaireModificationIngredient.html
{% extends 'applipizza/base.html' %}

{% block title %}Modification ingrédient{% endblock %}

{% block main %}
<div class="container-fluid"><h2>Modification ingrédient {{ingredient.nom}}</h2></div>
<hr>
<div class="container">
    <form action="/ingredients/{{ingredient.idIngredient}}/updated/" method="post">
        {% csrf_token %}
        <div class="mb-3">
        <label for="id_nomIngredient">Nom de l'ingrédient</label>
        <input type="text" class="form-control" name="nomIngredient" value="{{ingredient.nomIngredient}}" required id="id_nomIngredient" maxlength="50">
        </div>
        <button type="submit" class="btn btn-dark">Envoyer</button>
    </form>
</div>
{% endblock %}

webpizza/applipizza/templates/applipizza/formulaireModificationPizza.html
{% extends 'applipizza/base.html' %}

{% block title %}Modification d'une pizza{% endblock %}

{% block main %}
<div class="container-fluid"><h2>Modification pizza {{pizza.nom}}</h2></div>
<hr>
<div class="container">
    <form enctype="multipart/form-data" action="/pizzas/{{pizza.idPizza}}/updated/" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_nomPizza">Nom de la pizza</label>
            <input type="text" class="form-control" name="nomPizza" required id="id_nomPizza" maxlength="50" value="{{pizza.nomPizza}}">
        </div>
        
        <div class="mb-3" class="form-label">
            <label for="id_prix_Pizza">Prix de la pizza</label>
            <input type="number" class="form-control" name="prix" required id="id_prix_Pizza" maxlength="50" step="0.01" min="0" value="{{pizza.prix}}">
        </div>
        <div class="classIMG d-flex justify-content-center">
            <img class="imagePizza" src="{{MEDIA_URL}}{{pizza.image}}" alt="image-pizza" title="{{pizza.nomPizza}}" width="640px" height="480px">
        </div>
        <div class="classNOM d-flex justify-content-center"><i>Fichier actuel : {{pizza.image}}.</i></div>
        <div class="mb-3" class="form-label">
            <label for="id_image" >Nouveau Fichier image</label>
            <input  class="form-control" name="image" type="file" id="id_image" accept="image/*">
        </div>
        <button type="submit" class="btn btn-dark">Envoyer</button>
    </form>
</div>
{% endblock %}

webpizza/applipizza/templates/applipizza/pizza.html
{% extends 'applipizza/base.html' %}

{% block title %}Détails d'une pizza{% endblock %}

{% block main %}
<h2> {{pizza.nomPizza}}</h2>
{% if ingredientsPizza|length == 0 %}
<p>{{pizza}}</p>
<div class="container center">
  <div class="container"><p>La pizza {{pizza.nomPizza}} n'a pas encore d'ingrédient !</p></div>
</div>
{% else %}
<div class="container">
  <div class="card card-style m-5">
    <div class="row g-0">
      <div class="col-md-6 col-lg-6 d-none d-md-block">
        <img src="{{MEDIA_URL}}{{pizza.image}}" alt="image de pizza" title="{{pizza.nomPizza}}" class="card-img-top"/>
      </div>
      <div class="col-md-6 col-lg-6 align-items-center">
        <div class="table-responsive m-3">
          <table class="table table-borderless">
              <thead> 
                <tr>
                  <th scope="col">Ingrédient</th>
                  <th scope="col">Quantité</th>
                  {% if user.is_staff %}
                  <th scope="col">Action</th>
                  {% endif %}
                </tr>
              </thead>
              <tbody>
                {% for ingredient in ingredientsPizza%}
                <tr>
                  <th scope="row">{{ingredient.nomIngredient}}</th>
                  <td>{{ingredient.quantite}}</td>
                  {% if user.is_staff %}
                  <td><a class="lien-style" href="/pizzas/{{pizza.idPizza}}/deleteIngredient/{{ingredient.idCompo}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                    <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                  </svg></a></td>
                </tr>
                {% endif %}
                {% endfor %}
              </tbody>
            </table>
        </div>
      </div>
    </div>
    {% if user.is_authenticated and user.is_staff == False %}
    <div class="card-footer">
      <div class="container d-flex justify-content-center">
        <a class="btn btn-outline-success m-2" href="/pizzas/{{pizza.idPizza}}/buy/">
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-basket2" viewBox="0 0 16 16">
            <path d="M4 10a1 1 0 0 1 2 0v2a1 1 0 0 1-2 0v-2zm3 0a1 1 0 0 1 2 0v2a1 1 0 0 1-2 0v-2zm3 0a1 1 0 1 1 2 0v2a1 1 0 0 1-2 0v-2z"/>
            <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-.623l-1.844 6.456a.75.75 0 0 1-.722.544H3.69a.75.75 0 0 1-.722-.544L1.123 8H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM2.163 8l1.714 6h8.246l1.714-6H2.163z"/>
          </svg>
        </a>
      </div>
      {% endif %}

  </div>
  </div>
</div>
{% endif %}
{% if user.is_staff %}
<!-- Ajout ingrédient -->
<h2>Aouter un ingrédient à la pizza</h2>
<div class=" container">
  <form action="/pizzas/{{pizza.idPizza}}/addIngredient/" method="post">
    {% csrf_token %}
    <div class="mb-3">
    <label for="id_ingredient">Ingrédient</label>
    <select class="form-select" name="ingredient" required id="id_ingredient">
      <option value="">Choississez l'ingrédient à ajouter</option>
      {% for ing in ingredients %}
      <option value="{{ing.idIngredient}}">{{ing.nomIngredient}}</option>
      {% endfor %}
    </select>
    </div>
    <div class="mb-3">
      <label for="id_quantite">Quantité</label>
      <input type="text" class="form-control" name="quantite" required id="id_quantite" maxlength="100">
      </div>
    <button type="submit" class="btn btn-dark">Envoyer</button>
</form>
</div>
{% endif %}
{% endblock %}

webpizza/applipizza/templates/applipizza/traitementFormulaireCreationIngredient.html
{% extends 'applipizza/base.html' %}

{% block title%}Ingrédient Créé{% endblock %}

{% block main %}
<h2>Création d'un ingrédient</h2>
<p>L'ingrédient "{{nom}}" a été créé.</p>
{% endblock %}

webpizza/applipizza/templates/applipizza/traitementFormulaireCreationPizza.html
{% extends 'applipizza/base.html' %}

{% block title%}Ingrédient Créé{% endblock %}

{% block main %}
<h2>Création d'une Pizza</h2>
<p>La pizza "{{nom}}" a été créé.</p>
{% endblock %}

webpizza/applipizza/templates/applipizza/traitementFormulaireModificationIngredient.html
{% extends 'applipizza/base.html' %}

{% block title%}Ingrédient modifié{% endblock %}

{% block main %}
<h2>Modification d'un Ingrédient</h2>
<p>L'ingrédient "{{ingredient.nomIngredient}}" a été modifié.</p>
{% endblock %}